all:
	javac Animal.java
	javac AreaEffect.java
	javac BedOfSpikes.java
	javac Buffs.java
	javac Character.java
	javac Door.java
	javac EffectType.java
	javac Food.java
	javac GlobalLevel.java
	javac HealthEffect.java
	javac InteractiveItem.java
	javac Inventory.java
	javac Item.java
	javac ItemType.java
	javac LevelUpEffect.java
	javac NoneEffect.java
	javac NoneItem.java
	javac ObstacleItem.java
	javac OneShotBananaPeel.java
	javac OneShotBook.java
	javac OneShotHealthPot.java
	javac OneShotItem.java
	javac ReadFiles.java
	javac SaveFile.java
	javac TakeableItem.java
	javac TakeableKey.java
	javac TakeableSword.java
	javac Terrain.java
	javac Tile.java
	javac Wall.java
	javac Write.java
	javac Zone.java
	javac DeathView.java
	javac GlobalGameplayView.java
	javac InGameMenuView.java
	javac InventoryView.java
	javac LoadGameView.java
	javac LocalGameplayView.java
	javac MainMenuView.java
	javac NewGameView.java
	javac SaveGameView.java
	javac StatusView.java
	javac DeathController.java
	javac GlobalGameplayController.java
	javac InGameMenuController.java
	javac InGameMenuListener.java
	javac InventoryController.java
	javac InventoryListener.java
	javac LoadGameController.java
	javac LocalGameplayController.java
	javac MainMenuController.java
	javac NewGameController.java
	javac SaveGameController.java